packages:
  - apps/*
  - packages/*

catalog:
  "@biomejs/biome": 2.3.8
  "@dotenvx/dotenvx": 1.51.1
  "@types/node": 24.10.1
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  better-typescript-lib: 2.12.0
  react: 19.2.1
  react-dom: 19.2.1
  typescript: 5.9.3

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@cloudflare/*"
  - "@next/*"
  - "@opennextjs/*"
  - miniflare
  - next
  - react
  - react-dom
  - wrangler

trustPolicy: no-downgrade
