packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 2.3.8
  '@dotenvx/dotenvx': 1.51.1
  '@types/node': 24.10.1
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  react: 19.2.1
  react-dom: 19.2.1
  typescript: 5.9.3

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - '@cloudflare/*'
  - '@tanstack/*'
  - miniflare
  - react
  - react-dom
  - wrangler

trustPolicy: no-downgrade

trustPolicyExclude:
  - '@noble/ciphers@2.0.1'
  - semver@6.3.1
  - undici-types@6.20.0
